config/routes.rb
Rails.application.routes.draw do

  # root   'static_pages#savedate'
  root   'static_pages#home'
  get    '/savethedate',  to: 'static_pages#savedate'
  get    '/home',         to: 'static_pages#home'
  get    '/godzillamode'   => 'guests#index'
  get    '/guests',       to: 'guests#new'
  get    '/rsvp',         to: 'guests#new'
  post   '/rsvp',         to: 'guests#create'
  patch  '/rsvp',         to: 'guests#update'
  get    '/check',        to: 'sessions#new'
  post   '/check',        to: 'sessions#create'
  delete '/check_out',    to: 'sessions#destroy'
  resources :guests,    only: [:new, :create, :show, :edit, :update, :destroy]
  resources :attendees, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :songs,     only: [:index, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :guest, optional: true
  # default_scope -> { order(updated_at: :desc) }
  # validates :guest_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :child, inclusion: { in: [ true, false ] }
  validates :welcome_dinner, inclusion: { in: [ true, false ] }
  validates :yoga, inclusion: { in: [ "","7am","9am","11am" ] }
  validates :reception_dinner, inclusion: { in: [ true, false ] }
  validates :vegan, inclusion: { in: [ true, false ] }
  # validates :food_restrictions
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :attendees
  has_many :songs
  accepts_nested_attributes_for :attendees, 
    reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :songs,
    reject_if: lambda {|attributes| attributes['artist'].blank? && attributes['title'].blank?}
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def self.to_csv
    attributes = %w{ 
      guest_id
      name
      unable_to_attend
      welcome_dinner
      yoga
      reception_dinner
      child
      vegan
      food_restrictions
      updated_at
    }
    guest_attributes = %w{
      email
    }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |guest|
          # csv << guest_attributes.map{ |attr| guest.send(attr) }
        guest.attendees.each do |a|
          csv << attributes.map{ |attr| a.send(attr) }
        end
      end
    end
  end


end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :guest, optional: true
  validates :artist, length: { maximum: 51 }
  validates :title, length: { maximum: 481 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def savedate
  end

  def home
  end

  private

    # Confirms a checked-in guest.
    def checked_in_guest
      unless checked_in?
        flash[:danger] = "Check for a reservation by entering your email address."
        redirect_to check_url
      end
    end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :checked_in_guest, only: [:new, :edit, :update, :destroy]

  def new
    @guest = current_guest

    1.times do
      @guest.songs.build
    end
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy
    flash[:success] = "Attendee removed"
    redirect_to request.referrer || guest_url
  end

  private

    def attendee_params
      params.require(:attendee).permit( 
        :id,
        :name,
        :child,
        :welcome_dinner,
        :yoga,
        :reception_dinner,
        :vegan,
        :food_restrictions
      )
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_action :checked_in_guest, only: [:show, :edit, :update, :destroy]
  before_action :correct_guest,    only: [:show, :edit, :destroy]

  def index
    @guests = Guest.all
    @attendees = Attendee.all

    respond_to do |format|
      format.html
      format.csv { send_data @guests.to_csv, filename: "guests-#{Date.today}.csv" }
    end
  end

  def show
    @guest = Guest.find(params[:id])
    @attendees = @guest.attendees
    @songs = @guest.songs
  end

  def new
    @guest = Guest.new

    # @attendee_card = []
    6.times do
      @guest.attendees.build
    end

    3.times do
      @guest.songs.build
    end
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      check @guest
      flash[:success] = "Thanks for your response!"
      redirect_to @guest 
    else
      render 'new'
    end
  end

  def edit
    # @guest = Guest.find(params[:id])
  end

  def update
    @guest = current_guest # WATCH OUT FOR THIS CHEEKY FUCKER
    if @guest.update_attributes(guest_params)
      flash[:success] = "Update successful"
      redirect_to @guest
    else
      render 'edit'
    end
  end

  def destroy
    Guest.find(params[:id]).destroy
    flash[:success] = "Guest deleted"
    redirect_to rsvp_url
  end

  private

    def guest_params
      params.require(:guest).permit(
        :name,
        :email,
        attendees_attributes: [
          :id,
          :name,
          :child,
          :welcome_dinner,
          :yoga,
          :reception_dinner,
          :vegan,
          :food_restrictions,
          :unable_to_attend
        ],
        songs_attributes: [
          :id,
          :artist,
          :title
        ])
    end

    # Before filters

    # Confirms the correct guest.
    def correct_guest
      @guest = Guest.find(params[:id])
      redirect_to(root_url) unless current_guest?(@guest)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    guest = Guest.find_by(email: params[:session][:email].downcase)
    if guest
      # Check the guest in and redirect to guest's show page (w/ rsvp details).
      check guest
      redirect_to guest
    else
      # Three-per-em space included after "go" to hack in whitespace
      flash.now[:danger] = "Reservation not found. Is this email address 
        correctly entered? If so, perhaps you need to go 
        #{view_context.link_to('RSVP', rsvp_path)}.".html_safe
      render 'new'
    end
  end

  def destroy
    check_out
    redirect_to home_url
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @guests = Guest.all
  end
  
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:success] = "Song removed"
    redirect_to request.referrer || guest_url
  end
  private

    def song_params
      params.require(:attendee).permit( 
        :id,
        :artist,
        :title
      )
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def savedate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Checks in the given guest.
  def check(guest)
    session[:guest_id] = guest.id
  end

  # Returns true if the given guest is the current guest.
  def current_guest?(guest)
    guest == current_guest
  end

  # Returns the current checked-in guest (if any).
  def current_guest
    @current_guest ||= Guest.find_by(id: session[:guest_id])
  end

  # Returns true if the guest is logged in (checked in), false otherwise.
  def checked_in?
    !current_guest.nil?
  end

  # Logs out the current guest.
  def check_out
    session.delete(:guest_id)
    @current_guest = nil
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attendees/_attendee.html.erb
<li>
  <%= attendee.name %><br/>
  <%= time_ago_in_words(attendee.updated_at) %> ago.
</li>

app/views/attendees/new.html.erb
<%= render "layouts/header" %>
<% provide(:button_text, "Add Attendee") %>


<section class="section_container" id="add_attendee">
  <h1 class="section_header">Add Attendee</h1>
<%= render "layouts/flasher" %>
  <p class="flex_center">
    You have <%= pluralize(@guest.attendees.count, "person") %> registered already:
  </p>
  <div class="flex_center">
    <table>
      <tr>
        <% @guest.attendees.order("created_at ASC").each do |a| %>
          <td><%= a.name %> ✔️</td>
        <% end %>
      </tr>
    </table>
  </div>
  <div>
    <%= form_for(@guest, url: rsvp_path) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.fields_for :attendees, Attendee.new do |attendee_form| %>
        <table class="attendee_row flex_center" id="add_attendee">
          <tr>
            <td><%= attendee_form.label :name, "##{ @guest.attendees.count + 1 }" %></td>
            <td><%= attendee_form.text_field :name, placeholder: "attendee name" %></td>
            <td><%= attendee_form.label :unable_to_attend, "cannot attend" %>
                <%= attendee_form.check_box :unable_to_attend %></td>
            <td>|</td>
            <td>will attend:</td>
            <td>
              <%= attendee_form.label :welcome_dinner %><%= attendee_form.check_box :welcome_dinner %></td>
            <td>
              <div class="tooltip">
                <%= attendee_form.label :yoga, "Yoga" %>
            <span class="tooltip_text"><%= render "shared/yoga_disclaimer" %></span>
              </div>
                <%= attendee_form.select :yoga, ["","7am","9am","11am"] %>
            </td>
            <td>
              <%= attendee_form.label :reception_dinner, "Ceremony & Reception" %><%= attendee_form.check_box :reception_dinner %></td>
            <td>|</td>
            <td>
              <%= attendee_form.label :child, "Child under 10" %><%= attendee_form.check_box :child %>
            </td>
            <td>
              <%= attendee_form.label :vegan %><%= attendee_form.check_box :vegan %></td>
            <td><%= attendee_form.text_field :food_restrictions, placeholder: "other" %></td>
          </tr>
        </table>

      <% end %>

      <%= render "shared/error_messages", object: f.object %>
      <div class="flex_center" id="submit_box">
        <%= f.submit yield(:button_text), class: "submit_button" %>
      </div>
    <% end %>
    <p class="flex_center">
      <%= link_to "Cancel", guest_path(current_guest), class: "emphasis" %>
    </p>
    <p>
      Are you not <%= @guest.name %>? You can <%= link_to("exit to the main page", check_out_path, method: "delete") %>, or <%= link_to("check here", check_path) %> for another reservation.
    </p>

  </div>
</section>

<%= render "layouts/tree_emblem" %>
<%= render "layouts/footer" %>

app/views/guests/_form.html.erb
<%= form_for(@guest, url: rsvp_path) do |f| %>

<div>
  <p>
    Please enter the names of those in your party, including yourself, and indicate which events each person would like to attend, or if they are unable to attend. If anyone in your group has certain dietary concerns or needs specific accomodations, please enter that information as well. 
  </p>
</div>
<table class="flex_center">
  <tr>
    <td class="midway"><%= f.label :name, "Your Name" %></td>
    <td><%= f.text_field :name, required: true %></td>
  </tr>
  <tr>
    <td class="midway"><%= f.label :email %></td>
    <td><%= f.email_field :email, required: true %></td>
  </tr>
  <tr>
    <td class="midway"><%= f.label :members_in_party %></td>
    <td>
      <%= select("members_in_party", "members_in_party", [1,2,3,4,5,6], { include_blank: false }) %>
    </td>
  </tr>
</table>

  <%= f.fields_for :attendees do |attendee_form| %>
    <table class="attendee_row flex_center hide_me" id=<%= "#{attendee_form.options[:child_index] + 1}" %>>
      <tr>
        <td><%= attendee_form.label :name, "##{attendee_form.options[:child_index] + 1}" %></td>
        <% if (attendee_form.options[:child_index] < 1) %>
        <td><%= attendee_form.text_field :name, placeholder: "your name", required: true %>
        <% else %>
        <td><%= attendee_form.text_field :name, placeholder: "attendee name" %>
        <% end %>
        </td>
        <td><%= attendee_form.label :unable_to_attend, "cannot attend" %>
            <%= attendee_form.check_box :unable_to_attend %></td>
        <td>|</td>
        <td>will attend:</td>
        <td>
          <%= attendee_form.label :welcome_dinner %><%= attendee_form.check_box :welcome_dinner %></td>
        <td>
          <div class="tooltip">
            <%= attendee_form.label :yoga, "Yoga" %>
            <span class="tooltip_text"><%= render "shared/yoga_disclaimer" %></span>
          </div>
          <%= attendee_form.select :yoga, ["","7am","9am","11am"] %>
        </td>
        <td>
          <%= attendee_form.label :reception_dinner, "Ceremony & Reception" %><%= attendee_form.check_box :reception_dinner %></td>
        <td>|</td>
        <td>
          <%= attendee_form.label :child, "Child under 10" %><%= attendee_form.check_box :child %>
        </td>
        <td>
          <%= attendee_form.label :vegan %><%= attendee_form.check_box :vegan %></td>
        <td><%= attendee_form.text_field :food_restrictions, placeholder: "other" %></td>
      </tr>
    </table>
  <% end %>

<h2>Music</h2>
<p>Be our DJ! We've decided to not have a professional DJ at the wedding. Instead we thought we'd ask our family and friends to share with us the music they love. Nominate the songs you would most like us to add to the party playlist.</p>

<%= f.fields_for :songs do |song_form| %>
  <table class="song_row flex_center">
    <tr>
      <td>
        <%= song_form.label "Song Request ##{song_form.options[:child_index] + 1}" %>
      </td>
      <td><%= song_form.text_field :artist, placeholder: "artist" %></td>
      <td><%= song_form.text_field :title, placeholder: "title" %></td>
    </tr>
  </table>
<% end %>

  <%= render "shared/error_messages", object: f.object %>

<div class="flex_center" id="submit_box">
  <%= f.submit yield(:button_text), class: "submit_button" %>
</div>

<% end %>

app/views/guests/edit.html.erb
<%= render "layouts/header" %>
<% provide(:button_text, "Confirm Changes") %>

<section class="section_container" id="edit">
  <h1 class="section_header">Edit Your Reservation</h1>
<%= render "layouts/flasher" %>
  <div>

    <%= form_for(@guest, url: rsvp_path) do |f| %>

    <h2>Contact Info</h2>
    <table class="flex_center">
      <tr>
        <td class="midway"><%= f.label :name, "Your Name" %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td class="midway"><%= f.label :email %></td>
        <td><%= f.email_field :email %></td>
      </tr>
    </table>

    <h2>Attendees (<%= @guest.attendees.count %>)</h2>
      <%= f.fields_for :attendees do |attendee_form| %>
        <table class="attendee_row flex_center">
          <tr>
            <td><%= attendee_form.text_field :name, placeholder: "attendee name" %></td>
            <td><%= attendee_form.label :unable_to_attend, "cannot attend" %>
                <%= attendee_form.check_box :unable_to_attend %></td>
            <td>|</td>
            <td>will attend:</td>
            <td>
              <%= attendee_form.label :welcome_dinner %><%= attendee_form.check_box :welcome_dinner %></td>
            <td>
              <div class="tooltip">
                <%= attendee_form.label :yoga, "Yoga" %>
                <span class="tooltip_text"><%= render "shared/yoga_disclaimer" %></span>
              </div>
              <%= attendee_form.select :yoga, ["","7am","9am","11am"] %>
            </td>
            <td>
              <%= attendee_form.label :reception_dinner, "Ceremony & Reception" %><%= attendee_form.check_box :reception_dinner %></td>
            <td>|</td>
            <td>
              <%= attendee_form.label :child, "Child under 10" %><%= attendee_form.check_box :child %>
            </td>
            <td>
              <%= attendee_form.label :vegan %><%= attendee_form.check_box :vegan %></td>
            <td><%= attendee_form.text_field :food_restrictions, placeholder: "other" %></td>
          </tr>
        </table>
      <% end %>

    <h2>Song Requests (<%= @guest.songs.count %>)</h2>

    <%= f.fields_for :songs do |song_form| %>
      <table class="song_row flex_center">
        <tr>
          <td>
            <%= song_form.label "Song Request ##{song_form.options[:child_index] + 1}" %>
          </td>
          <td><%= song_form.text_field :artist, placeholder: "artist" %></td>
          <td><%= song_form.text_field :title, placeholder: "title" %></td>
        </tr>
      </table>
    <% end %>

      <%= render "shared/error_messages", object: f.object %>

    <div class="flex_center" id="submit_box">
      <%= f.submit yield(:button_text), class: "submit_button" %>
    </div>

    <% end %>

    <p>
      Are you not <%= @guest.name %>? You can <%= link_to("exit to the main page", check_out_path, method: "delete") %>, or <%= link_to("check here", check_path) %> for another reservation.
    </p>

  </div>
</section>

<%= render "layouts/tree_emblem" %>
<%= render "layouts/footer" %>

app/views/guests/index.html.erb
<section id="index">
  <% if @guests.present? %>
  <h1 class="flex_center">GODZILLAMODE:ENGAGED</h1>
  <div class="flex_center">
    <%= image_tag("godzillamode.jpg", alt: "Godzilla Mode") %>
  </div>

  <p align="center">This data may also be downloaded as a <%= link_to("CSV file", "godzillamode.csv") %>. The last change was made <%= time_ago_in_words(@attendees.order("updated_at").last.updated_at) %> ago. (For <%= @attendees.order("updated_at").last.name %>.)



  <h2 class="flex_center">Party Heads</h2>
  <div class="flex_center">
    <table>
      <tr>
        <th>Guest Name</th>
        <th>Email Address</th>
        <th>Last Updated</th>
      </tr>
      <% @guests.order("updated_at DESC").each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.email %></td>
        <td><%= time_ago_in_words(guest.updated_at) %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <h2 class="flex_center">Attendee List</h2>
  <div class="flex_center">
    <table>
      <tr>
        <th>Assoc. Email</th>
        <th>Attendee Name</th>
        <th>Can't Come</th>
        <th>Welcome Dinner</th>
        <th>Yoga</th>
        <th>Reception Dinner</th>
        <th>Child</th>
        <th>Vegan</th>
        <th>Food Restrictions</th>
        <th>Last Updated</th>
      </tr>
      <% @guests.order("updated_at DESC").each do |guest| %>
        <% guest.attendees.each do |a| %>
            <tr>
              <td><%= guest.email %></td>
              <td><%= a.name %></td>
              <td><% if a.unable_to_attend? %>❌<% end %></td>
              <td>
                <% if a.welcome_dinner? %>✔️<% end %>  
              </td>
              <td><%= a.yoga %></td>
              <td>
                <% if a.reception_dinner? %>✔️<% end %>
              </td>
              <td>
                <% if a.child? %>✔️<% end %>
              </td>
              <td>
                <% if a.vegan? %>✔️<% end %>
              </td>
              <td><%= a.food_restrictions %></td>
              <td><%= time_ago_in_words(a.updated_at) %></td>
            </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <h2 class="flex_center">Song List</h2>
  <div class="flex_center">
    <table>
      <tr>
        <th>Assoc. Email</th>
        <th>Artist</th>
        <th>Title</th>
        <!-- <th>Last Updated</th> -->
      </tr>
      <% @guests.order("updated_at ASC").each do |guest| %>
        <% guest.songs.each do |a| %>
            <tr>
              <td><%= guest.email %></td>
              <td><%= a.artist %></td>
              <td><%= a.title %></td>
              <!-- <td><%= time_ago_in_words(a.updated_at) %></td> -->
            </tr>
        <% end %>
      <% end %>
    </table>
  </div>

<% else %>
  <div class="flex_center">
    <%= image_tag("godzilla.jpg", alt: "Pretty in Pink") %>
  </div>
  <p class="flex_center">(no guest responses)</p>
<% end %>

</section>

app/views/guests/new.html.erb
<%= render "layouts/header" %>
<%= render "layouts/flasher" %>
<% provide(:button_text, "Submit Response") %>

<section class="section_container" id="rsvp_page">
  <h1 class="section_header">RSVP</h1>
      <div class="flex_center">
        <%= image_tag "solo_tree.png", height: "150px" %>
        <%= image_tag "three_trees.png", height: "150px" %>
        <%= image_tag "two_trees.png", height: "150px" %>
      </div>
  <div>
    <div class="section_thirds group">
      <h2>Organized Events</h2>
      <div class="flex_center">
        <p id="guests_welcome">Guests are welcome to attend any or all events.</p>
      </div>
      <div class="col span_1_of_3">
        <h3>Welcome Dinner</h3>
        <p class="triplet_para">
          Join us Friday night as we start the weekend off. We’ll be serving a casual dinner at the Gazebo starting 6pm.
        </p>
      </div>
      <div class="col span_1_of_3">
        <h3>Morning Yoga</h3>
        <p class="triplet_para">
          Saturday morning, Ryan’s friend from college, <%= link_to("Emily Rollie", "http://www.emilyrollie.com/yoga", target: "_blank") %>, will be joining us and leading three yoga classes in the Tom Tom Yurt. Sessions begin at 7am, 9am, and 11am. Available mats and towels to borrow are limited, please bring your own if you have them.
          <span class="tooltip" id="read_disclaimer">
            Please read and agree
            <span class="tooltip_text">
              <%= render "shared/yoga_disclaimer" %>
            </span>
          </span>.
        </p>
      </div>
      <div class="col span_1_of_3">
        <h3>Ceremony & Reception</h3>
        <p class="triplet_para">
          Saturday evening, we host the wedding ceremony and reception dinner. Festivities kick off with pre-ceremony snacks and drinks at 4:30pm. Reception food is vegetarian.
        </p>
      </div>

    </div>
    <h2>Your Party</h2>
    <%= render "form" %>

    <p>
      <% if checked_in? %>
        It appears you have already started filling out a reservation. See your <%= link_to("Existing Reservation", current_guest, class: "emphasis") %>.
      <% else %>
        Have you filled out this form before? Check for an <%= link_to("existing reservation", check_path) %>.
      <% end %>
    </p>
  </div>
</section>

<%= render "layouts/tree_emblem" %>
<%= render "layouts/footer" %>




<!-- 






 -->

app/views/guests/show.html.erb
<%= render "layouts/header" %>
<% provide(:button_text, "add") %>


<section class="section_container" id="reservation">
  <h1 class="section_header">Your Reservation</h1>
<%= render "layouts/flasher" %>
  <div>
    <%= form_for(@guest, url: rsvp_path) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

    <h2>Contact Info</h2>

    <table class="flex_center">
      <tr>
        <td><%= f.label :name, "Your Name" %></td>
        <td><%= @guest.name %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= @guest.email %></td>
      </tr>
    </table>

    <div class="">
      <% if @guest.attendees.any? %>
        <h2>Attendees (<%= @guest.attendees.count %>)</h2>
        <% @guest.attendees.order("created_at ASC").each do |a| %>
        <table class="attendee_row flex_center">
          <tr>
          <% if a.unable_to_attend? %>
            <td><%= a.name %> is unable to attend: ✔️</td>
          <% else %>
            <td><%= a.name %> will attend:</td>

            <% if a.welcome_dinner? %>
            <td>Welcome Dinner: ✔️</td>
            <% end %>  

            <% if a.yoga? %>
            <td>Morning Yoga at <%= a.yoga %>: ✔️</td>
            <% end %>

            <% if a.reception_dinner? %>
            <td>Ceremony & Reception: ✔️</td>
            <% end %>

            <% if a.child? || a.vegan? || a.food_restrictions? %>
            <td>|</td>
            <% end %>

            <% if a.child? %>
            <td>Child under 10: ✔️</td>
            <% end %>

            <% if a.vegan? %>
            <td>Vegan: ✔️</td>
            <% end %>
          
            <% if a.food_restrictions? %>
            <td>NB: <%= a.food_restrictions %>: ✔️</td>
            <% end %>
          <% end %>
          <td>
            <%= link_to "✕", a, method: :delete %>
          </td>
          </tr>
        </table>

        <% end %>
      <% end %>
    </div>
    <p class="flex_center">
      <%= link_to "Add Attendee", new_attendee_path(current_guest) %>
    </p>

    <div>
        <h2>Song Requests (<%= @guest.songs.count %>)</h2>
      <% if @guest.songs.any? %>
        <% @guest.songs.order("created_at ASC").each do |s| %>
      <table class="song_row flex_center">
        <tr>
          <td>
            <% if s.artist? %>
              Artist: <%= s.artist %>
            <% else %>
              <small>none</small>
            <% end %>
          </td>
          <td>
            <% if s.title? %>
              Title: <%= s.title %>
            <% else %>
              <small>none</small>
            <% end %>
          </td>
          <td>
            <%= link_to "✕", s, method: :delete %>
          </td>
        </tr>
      </table>
      <% end %>
      <% end %>

      <%= f.fields_for :songs, Song.new do |song_form| %>
        <table class="song_row flex_center">
          <tr>
            <td>
              <%= song_form.label "Just One More:" %>
            </td>
            <td><%= song_form.text_field :artist, placeholder: "artist" %></td>
            <td><%= song_form.text_field :title, placeholder: "title" %></td>
            <td><%= f.submit yield(:button_text) %></td>
          </tr>
        </table>
      <% end %>
    </div>

    <p class="flex_center">
      <%= link_to "Edit Reservation", edit_guest_path(current_guest) %>
    </p>
    <p>
      Are you not <%= @guest.name %>? You can <%= link_to("exit to the main page", check_out_path, method: "delete") %>, or <%= link_to("check here", check_path) %> for another reservation.
    </p>
    <% end %>

  </div>
</section>

<%= render "layouts/tree_emblem" %>
<%= render "layouts/footer" %>

app/views/layouts/_flasher.html.erb
<% flash.each do |message_type, message| %>
    <div class="flex_center emphasis alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav id="navbar">
  <div>
    <ul class="topnav">
      <li class="left">
        <%= link_to("⌂", home_path) %> 
      </li>
      <li>
        <%= link_to("Registry", home_path + "#registry") %>
      </li>
      <li >
        <%= link_to("Venue", home_path + "#venue") %>
      </li>
      <li>
        <%= link_to("Activities", home_path + "#activities") %>
      </li>
      <li>
        <%= link_to("Schedule", home_path + "#schedule") %>
      </li>
      <li>
        <%= link_to("Lodging", home_path + "#lodging") %>
      </li>
      <li>
        <% if checked_in? %>
          <%= link_to(current_guest.name, current_guest, class: "active") %>
        <% else %>
          <%= link_to("RSVP", rsvp_path, class: "active") %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_html5shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->